### ISSUE TITLE
Not sure if this is what you expected…

### ISSUE THREAD

**Issue by aarongustafson** [BringMeToLight/project#2]
Here’s the deployed server: http://bring-me-to-light-10kapart2016.azurewebsites.net/

**Comment by BringMeToLight** [comment]
Final files are in BUILD. Did you try to use it?

**Comment by aarongustafson** [comment]
Ah, we use the project root as the rot folder. Can you add a web.config file to point Azure to that folder instead?

**Comment by BringMeToLight** [comment]
I don't know Azure, but I have two ideas :)
1. You can add "/build" to link, and after the project is correct: http://bring-me-to-light-10kapart2016.azurewebsites.net/build/
2. I can remove all files from Github and add only 4files, which we need for our project.

What solution will be better for you?

**Comment by aarongustafson** [comment]
Deploy is working now (I found a setting that let me change the root folder). Can you think of a way to make your project more accessible? Maybe at least adding keyboard controls?

**Comment by BringMeToLight** [comment]
Thank you for a good advice how ti improve project. We have had similar thoughts too and we will try to apply them soon... Of course there is still the limit 10kB :))

**Comment by aarongustafson** [comment]
:-)

**Comment by BringMeToLight** [comment]
We have just added more accessible approach via tab and focus. You can try it :)
